/**
 * Gripwell - Master SKU & Product Catalog Data
 * Extracted directly from Google Stitch Screen 7:
 * "Owner Settings: Manage Products (Mobile)" (5f8452ef383a4b69b6ef73cf3549d3a4)
 */

import { ProductKPISummary, ProductSKU } from "../types/models";

export const PRODUCT_CATEGORIES = [
  "All (14)",
  "Furniture & Seating",
  "Industrial Crates",
  "Packaging",
  "Oils & Agro",
] as const;

export const INITIAL_PRODUCT_KPIS: ProductKPISummary = {
  totalSkus: 14,
  totalSkusTag: "Live",
  rateUpdates: 2,
  rateUpdatesTag: "Today",
  avgMargin: "24.5%",
};

export const INITIAL_PRODUCTS: ProductSKU[] = [
  {
    id: "PRD-101",
    sku: "#PRD-101",
    name: "Plastic Chair (Standard)",
    category: "Furniture & Seating",
    categoryTag: "Seating",
    status: "ACTIVE",
    unitMetric: "pcs",
    defaultBaseRate: 180.0,
    defaultPlusRate: 205.0,
    minThresholdRate: 160.0,
    rateDisplay: "₹180.00 / pc",
    warehouseStock: 420,
    warehouseStockDisplay: "420 pcs",
    stockSubtext: "(Min dispatch: 10)",
    hsnCode: "3926.90",
  },
  {
    id: "PRD-204",
    sku: "#PRD-204",
    name: "Crate 20L (Heavy Duty)",
    category: "Industrial Crates",
    categoryTag: "Industrial",
    status: "ACTIVE",
    unitMetric: "unit",
    defaultBaseRate: 220.0,
    defaultPlusRate: 250.0,
    minThresholdRate: 195.0,
    rateDisplay: "₹220.00 / unit",
    warehouseStock: 185,
    warehouseStockDisplay: "185 pcs",
    stockSubtext: "(Min dispatch: 5)",
    hsnCode: "3923.10",
  },
  {
    id: "PRD-109",
    sku: "#PRD-109",
    name: "Plastic Table (Moulded 4-S)",
    category: "Furniture & Seating",
    categoryTag: "Furniture",
    status: "ACTIVE",
    unitMetric: "unit",
    defaultBaseRate: 850.0,
    defaultPlusRate: 950.0,
    minThresholdRate: 750.0,
    rateDisplay: "₹850.00 / unit",
    warehouseStock: 64,
    warehouseStockDisplay: "64 pcs",
    stockSubtext: "(Min dispatch: 2)",
    hsnCode: "9403.70",
  },
  {
    id: "PRD-202",
    sku: "#PRD-202",
    name: "Crate 10L (Standard)",
    category: "Industrial Crates",
    categoryTag: "Industrial",
    status: "ACTIVE",
    unitMetric: "unit",
    defaultBaseRate: 95.0,
    defaultPlusRate: 110.0,
    minThresholdRate: 82.0,
    rateDisplay: "₹95.00 / unit",
    warehouseStock: 850,
    warehouseStockDisplay: "850 pcs",
    stockSubtext: "(Min dispatch: 20)",
    hsnCode: "3923.10",
  },
  {
    id: "PRD-401",
    sku: "#PRD-401",
    name: "Raw Coffee Beans (Bags)",
    category: "Oils & Agro",
    categoryTag: "Agro",
    status: "ACTIVE",
    unitMetric: "kg",
    defaultBaseRate: 118.75,
    defaultPlusRate: 132.0,
    minThresholdRate: 105.0,
    rateDisplay: "₹118.75 / kg",
    secondaryRateDisplay: "₹9,500 / 80kg bag",
    warehouseStock: 320,
    warehouseStockDisplay: "320 bags",
    stockSubtext: "Restock threshold: 500",
    hsnCode: "0901.11",
    isLowStock: false,
  },
  {
    id: "PRD-305",
    sku: "#PRD-305",
    name: "Cold-Pressed Oils (Drums)",
    category: "Oils & Agro",
    categoryTag: "Agro & Oils",
    status: "ACTIVE",
    unitMetric: "L",
    defaultBaseRate: 124.4,
    defaultPlusRate: 142.0,
    minThresholdRate: 110.0,
    rateDisplay: "₹124.40 / L",
    secondaryRateDisplay: "₹5,600 / 45L drum",
    warehouseStock: 94,
    warehouseStockDisplay: "94 drums",
    stockSubtext: "(4,230 L)",
    hsnCode: "1515.90",
  },
  {
    id: "PRD-501",
    sku: "#PRD-501",
    name: "Corrugated Packaging Boxes (Large)",
    category: "Packaging",
    categoryTag: "Packaging",
    status: "ACTIVE",
    unitMetric: "pcs",
    defaultBaseRate: 45.0,
    defaultPlusRate: 52.0,
    minThresholdRate: 38.0,
    rateDisplay: "₹45.00 / pc",
    warehouseStock: 1200,
    warehouseStockDisplay: "1,200 pcs",
    stockSubtext: "(Min dispatch: 50)",
    hsnCode: "4819.10",
  },
  {
    id: "PRD-502",
    sku: "#PRD-502",
    name: "Stretch Wrap Film 500mm",
    category: "Packaging",
    categoryTag: "Packaging",
    status: "ACTIVE",
    unitMetric: "roll",
    defaultBaseRate: 340.0,
    defaultPlusRate: 385.0,
    minThresholdRate: 300.0,
    rateDisplay: "₹340.00 / roll",
    warehouseStock: 250,
    warehouseStockDisplay: "250 rolls",
    stockSubtext: "(Min dispatch: 4)",
    hsnCode: "3920.10",
  },
  {
    id: "PRD-205",
    sku: "#PRD-205",
    name: "Molded Plastic Pallet 1200x1000",
    category: "Industrial Crates",
    categoryTag: "Industrial",
    status: "ACTIVE",
    unitMetric: "unit",
    defaultBaseRate: 1450.0,
    defaultPlusRate: 1620.0,
    minThresholdRate: 1300.0,
    rateDisplay: "₹1,450.00 / unit",
    warehouseStock: 140,
    warehouseStockDisplay: "140 pcs",
    stockSubtext: "(Min dispatch: 5)",
    hsnCode: "3923.90",
  },
  {
    id: "PRD-306",
    sku: "#PRD-306",
    name: "Refined Sunflower Oil (Tin)",
    category: "Oils & Agro",
    categoryTag: "Agro & Oils",
    status: "ACTIVE",
    unitMetric: "tin",
    defaultBaseRate: 1850.0,
    defaultPlusRate: 2080.0,
    minThresholdRate: 1650.0,
    rateDisplay: "₹1,850.00 / tin",
    warehouseStock: 180,
    warehouseStockDisplay: "180 tins",
    stockSubtext: "(15L per tin)",
    hsnCode: "1512.19",
  },
  {
    id: "PRD-201",
    sku: "#PRD-201",
    name: "Industrial Stacking Bin 5L",
    category: "Industrial Crates",
    categoryTag: "Industrial",
    status: "ACTIVE",
    unitMetric: "unit",
    defaultBaseRate: 62.0,
    defaultPlusRate: 72.0,
    minThresholdRate: 54.0,
    rateDisplay: "₹62.00 / unit",
    warehouseStock: 520,
    warehouseStockDisplay: "520 pcs",
    stockSubtext: "(Min dispatch: 25)",
    hsnCode: "3923.10",
  },
  {
    id: "PRD-105",
    sku: "#PRD-105",
    name: "Ergonomic Task Stool",
    category: "Furniture & Seating",
    categoryTag: "Seating",
    status: "ACTIVE",
    unitMetric: "pcs",
    defaultBaseRate: 490.0,
    defaultPlusRate: 550.0,
    minThresholdRate: 430.0,
    rateDisplay: "₹490.00 / pc",
    warehouseStock: 88,
    warehouseStockDisplay: "88 pcs",
    stockSubtext: "(Min dispatch: 2)",
    hsnCode: "9401.30",
  },
  {
    id: "PRD-504",
    sku: "#PRD-504",
    name: "HDPE Chemical Drum 200L",
    category: "Packaging",
    categoryTag: "Packaging",
    status: "ACTIVE",
    unitMetric: "drum",
    defaultBaseRate: 1250.0,
    defaultPlusRate: 1400.0,
    minThresholdRate: 1120.0,
    rateDisplay: "₹1,250.00 / drum",
    warehouseStock: 75,
    warehouseStockDisplay: "75 drums",
    stockSubtext: "(Heavy duty)",
    hsnCode: "3923.30",
  },
  {
    id: "PRD-402",
    sku: "#PRD-402",
    name: "Basmati Grain Sacks (50kg)",
    category: "Oils & Agro",
    categoryTag: "Agro",
    status: "ACTIVE",
    unitMetric: "bag",
    defaultBaseRate: 3200.0,
    defaultPlusRate: 3550.0,
    minThresholdRate: 2850.0,
    rateDisplay: "₹3,200.00 / bag",
    warehouseStock: 410,
    warehouseStockDisplay: "410 bags",
    stockSubtext: "(Premium grade)",
    hsnCode: "1006.30",
  },
];
