/**
 * Gripwell - Mock Gate Pass Dataset
 * Reflects digital gate passes issued at Dock Bay operations.
 */

import { GatePass } from "../types/models";

export const DEFAULT_GATE_PASS: GatePass = {
  id: "GP-04",
  loadSequence: "202410240004",
  issueDate: "Oct 24, 2024",
  issueTime: "02:45 PM",
  vehicleNumber: "TN 01 AB 1234",
  driverName: "Rajan Kumar",
  driverPhone: "+91 98421 90812",
  driverDl: "DL-0420110092812",
  customerName: "Sri Murugan Traders - Salem Hub",
  destinationHub: "Salem Hub, Yard 2",
  dockBay: "Dock Bay 3",
  supervisorName: "M. Vance",
  securitySealNumber: "SEAL-88421-TAMPER-SAFE",
  sealVerified: true,
  totalPieceCount: 80,
  items: [
    {
      id: "gp-item-1",
      description: "Plastic Chair Standard",
      quantity: 50,
      unit: "Units",
      packaging: "Carton (5 × 10)",
      bayId: "Bay-3-A12",
    },
    {
      id: "gp-item-2",
      description: "Crate 20L Heavy Duty",
      quantity: 30,
      unit: "Units",
      packaging: "Palletized, Strapped",
      bayId: "Bay-3-B04",
    },
  ],
  ratesMasked: true,
  gateStatus: "authorized",
  smsNotificationSent: true,
  qrCodeValue: "FLEETBILL-GATEPASS-GP04-202410240004-SEAL88421",
};

export const RECENT_GATE_PASSES: GatePass[] = [
  DEFAULT_GATE_PASS,
  {
    id: "GP-03",
    loadSequence: "202410240003",
    issueDate: "Oct 24, 2024",
    issueTime: "01:15 PM",
    vehicleNumber: "TN 11 EF 9090",
    driverName: "Murugan",
    driverPhone: "+91 99443 32211",
    driverDl: "DL-0420080019283",
    customerName: "Anbu Furniture",
    destinationHub: "Coimbatore Hub",
    dockBay: "Dock Bay 5",
    supervisorName: "M. Vance",
    securitySealNumber: "SEAL-88419-TAMPER-SAFE",
    sealVerified: true,
    totalPieceCount: 100,
    items: [
      {
        id: "gp-item-3",
        description: "Crate 10L Standard",
        quantity: 100,
        unit: "Units",
        packaging: "Strapped Bundle",
        bayId: "Bay-5-C01",
      },
    ],
    ratesMasked: true,
    gateStatus: "exited",
    exitTimestamp: "01:28 PM",
    smsNotificationSent: true,
    qrCodeValue: "FLEETBILL-GATEPASS-GP03-202410240003-SEAL88419",
  },
  {
    id: "GP-02",
    loadSequence: "202410240002",
    issueDate: "Oct 24, 2024",
    issueTime: "11:35 AM",
    vehicleNumber: "TN 22 CD 5678",
    driverName: "R. Pandian",
    driverPhone: "+91 98450 01122",
    driverDl: "DL-0420150033412",
    customerName: "KK Stores",
    destinationHub: "Tiruppur Hub",
    dockBay: "Dock Bay 1",
    supervisorName: "M. Vance",
    securitySealNumber: "SEAL-88415-TAMPER-SAFE",
    sealVerified: true,
    totalPieceCount: 10,
    items: [
      {
        id: "gp-item-4",
        description: "Plastic Table (Heavy Mold)",
        quantity: 10,
        unit: "Units",
        packaging: "Shrink-wrapped",
        bayId: "Bay-1-A04",
      },
    ],
    ratesMasked: true,
    gateStatus: "exited",
    exitTimestamp: "11:50 AM",
    smsNotificationSent: true,
    qrCodeValue: "FLEETBILL-GATEPASS-GP02-202410240002-SEAL88415",
  },
];
